In [2]:
import numpy as np
arr1 = np.array([10,20,30,40,50,60,70,80,90,100])
print(arr1)

[ 10  20  30  40  50  60  70  80  90 100]


In [78]:
import numpy as np
arr2 = np.array([[10,20,30,40],[1,2,3,4],[1.1,2.2,3.3,4.4]])
print (arr2)
n=arr2[2,1]
print(n)

[[10.  20.  30.  40. ]
 [ 1.   2.   3.   4. ]
 [ 1.1  2.2  3.3  4.4]]
2.2


In [76]:
import numpy as np
arr3 = np.array([[[10,20,30,40],[1,2,3,4],[1.1,2.2,3.3,4.4]],[[11,22,33,44],[111,222,333,444],[11.1,22.2,33.3,44.4]],[[100,200,300,400],[101,201,301,401],[1.11,2.22,3.33,4.44]]])
print (arr3)
print (arr3[1,1,3])

[[[ 10.    20.    30.    40.  ]
  [  1.     2.     3.     4.  ]
  [  1.1    2.2    3.3    4.4 ]]

 [[ 11.    22.    33.    44.  ]
  [111.   222.   333.   444.  ]
  [ 11.1   22.2   33.3   44.4 ]]

 [[100.   200.   300.   400.  ]
  [101.   201.   301.   401.  ]
  [  1.11   2.22   3.33   4.44]]]
444.0


In [18]:
import numpy as np
arr1 = np.array([10,20,30,40])
print (arr1)
print(arr1.shape)

[10 20 30 40]
(4,)


In [19]:
import numpy as np
arr2 = np.array([[10,20,30,40],[1,2,3,4],[1.1,2.2,3.3,4.4]])
print (arr2)
n=arr2[2,1]
print(n)
print(arr2.shape)

[[10.  20.  30.  40. ]
 [ 1.   2.   3.   4. ]
 [ 1.1  2.2  3.3  4.4]]
2.2
(3, 4)


In [20]:
import numpy as np
arr3 = np.array([[[10,20,30,40],[1,2,3,4],[1.1,2.2,3.3,4.4]],[[11,22,33,44],[111,222,333,444],[11.1,22.2,33.3,44.4]],[[100,200,300,400],[101,201,301,401],[1.11,2.22,3.33,4.44]]])
print (arr3)
print (arr3[1,1,3])
print(arr3.shape)

[[[ 10.    20.    30.    40.  ]
  [  1.     2.     3.     4.  ]
  [  1.1    2.2    3.3    4.4 ]]

 [[ 11.    22.    33.    44.  ]
  [111.   222.   333.   444.  ]
  [ 11.1   22.2   33.3   44.4 ]]

 [[100.   200.   300.   400.  ]
  [101.   201.   301.   401.  ]
  [  1.11   2.22   3.33   4.44]]]
444.0
(3, 3, 4)


In [23]:
import numpy as np
arr4 = np.array([10,20,30,40,50,60,70,80,90,100])
arr4=arr4.reshape(2,5)
print(arr4)



[ 10  20  30  40  50  60  70  80  90 100]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [4]:
import numpy as np
arr4 = np.array([10,20,30,40,50,60,70,80,90,100])
arr4=arr4.reshape(2,5)
print(arr4)
arr4=arr4.reshape(1,10)
print(arr4)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
[[ 10  20  30  40  50  60  70  80  90 100]]


In [39]:
import numpy as np
arr4 = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200,210,220,230,240])
arr4=arr4.reshape(3,2,4)
print(arr4)
#the multiple of length of the martix will give the matrix

[[[ 10  20  30  40]
  [ 50  60  70  80]]

 [[ 90 100 110 120]
  [130 140 150 160]]

 [[170 180 190 200]
  [210 220 230 240]]]


In [45]:
import numpy as np
arr1 = np.zeros([4,3])
print (arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [52]:
import numpy as np
arr1 = np.ones([3,2,2])
print (arr1)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [53]:
import numpy as np
arr1 = np.full([3,2,2],9)
print (arr1)

[[[9 9]
  [9 9]]

 [[9 9]
  [9 9]]

 [[9 9]
  [9 9]]]


In [64]:
import numpy as np
arr1 = np.eye(4)
print (arr1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [69]:
import numpy as np
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])
arr3=arr1+arr2
arr4=arr1-arr2
arr5=arr1*arr2
arr6=arr1//arr2
print (arr3)
print (arr4)
print (arr5)
print (arr6)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10 10 10 10]


In [9]:
import numpy as np
arr1 = np.array([[1,2,3,4],[11,22,33,44]])
arr2 = np.array([[10,20,30,40],[1,2,3,4]])
arr3=arr1+arr2
arr4=arr1-arr2
arr5=arr1*arr2
arr6=arr1//arr2
print (arr3)
print (arr4)
print (arr5)
print (arr6)



[[11 22 33 44]
 [12 24 36 48]]
[[ -9 -18 -27 -36]
 [ 10  20  30  40]]
[[ 10  40  90 160]
 [ 11  44  99 176]]
[[ 0  0  0  0]
 [11 11 11 11]]


In [13]:
import numpy as np
arr1 = np.array([[[10,20,30,40],[1,2,3,4],[1.1,2.2,3.3,4.4]],[[11,22,33,44],[111,222,333,444],[11.1,22.2,33.3,44.4]],[[100,200,300,400],[101,201,301,401],[1.11,2.22,3.33,4.44]]])
arr2 = np.array([[[10,20,30,40],[1,2,3,4],[1.1,2.2,3.3,4.4]],[[11,22,33,44],[111,222,333,444],[11.1,22.2,33.3,44.4]],[[100,200,300,400],[101,201,301,401],[1.11,2.22,3.33,4.44]]])
arr3=arr1+arr2
arr4=arr1-arr2
arr5=arr1*arr2
arr6=arr1//arr2
print (arr3)
print (arr4)
print (arr5)
print (arr6)

[[[ 20.    40.    60.    80.  ]
  [  2.     4.     6.     8.  ]
  [  2.2    4.4    6.6    8.8 ]]

 [[ 22.    44.    66.    88.  ]
  [222.   444.   666.   888.  ]
  [ 22.2   44.4   66.6   88.8 ]]

 [[200.   400.   600.   800.  ]
  [202.   402.   602.   802.  ]
  [  2.22   4.44   6.66   8.88]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1.00000e+02 4.00000e+02 9.00000e+02 1.60000e+03]
  [1.00000e+00 4.00000e+00 9.00000e+00 1.60000e+01]
  [1.21000e+00 4.84000e+00 1.08900e+01 1.93600e+01]]

 [[1.21000e+02 4.84000e+02 1.08900e+03 1.93600e+03]
  [1.23210e+04 4.92840e+04 1.10889e+05 1.97136e+05]
  [1.23210e+02 4.92840e+02 1.10889e+03 1.97136e+03]]

 [[1.00000e+04 4.00000e+04 9.00000e+04 1.60000e+05]
  [1.02010e+04 4.04010e+04 9.06010e+04 1.60801e+05]
  [1.23210e+00 4.92840e+00 1.10889e+01 1.97136e+01]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]


In [34]:

n=int(input("enter the size of array"))
arr=[]
for i in range(0,n):
    e=int(input("enter the number"))
print(arr)

enter the size of array4
enter the number6
enter the number7
enter the number7
enter the number9
[]
